name: Haskell CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GHC
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: 'latest'
    - name: Build
      run: cabal build
    - name: Test
      run: cabal test
